ALTER TABLE cvs_file_data
DROP COLUMN IF EXISTS SUMLEV,
DROP COLUMN IF EXISTS REGION,
DROP COLUMN IF EXISTS DIVISION,
DROP COLUMN IF EXISTS STATE,
DROP COLUMN IF EXISTS COUNTY,
DROP COLUMN IF EXISTS STNAME,
DROP COLUMN IF EXISTS CTYNAME,
DROP COLUMN IF EXISTS CENSUS2010POP;
